//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dive.Core.Assets {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinRE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinRE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dive.Core.Assets.WinRE", typeof(WinRE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- AddDiagnosticsToolToBootMenu.xml --&gt;
        ///&lt;BootShell&gt;
        ///	&lt;WinRETool locale=&quot;en-us&quot;&gt;
        ///		&lt;Name&gt;Dive&lt;/Name&gt;
        ///		&lt;Description&gt;Install, capture and tweak Windows on this device.&lt;/Description&gt;
        ///	&lt;/WinRETool&gt;
        ///	&lt;WinRETool locale=&quot;de-de&quot;&gt;
        ///		&lt;Name&gt;Dive&lt;/Name&gt;
        ///		&lt;Description&gt;Installiere, erfasse und optimiere Windows auf diesem Gerät.&lt;/Description&gt;
        ///	&lt;/WinRETool&gt;
        ///&lt;/BootShell&gt; ähnelt.
        /// </summary>
        internal static string AddDiagnosticsToolToBootMenu {
            get {
                return ResourceManager.GetString("AddDiagnosticsToolToBootMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- WinREConfig.xml --&gt;
        ///&lt;Recovery&gt;
        ///	&lt;RecoveryTools&gt;
        ///		&lt;RelativeFilePath&gt;Dive\Dive.exe&lt;/RelativeFilePath&gt;
        ///		&lt;CommandLineParam&gt;&lt;/CommandLineParam&gt;
        ///	&lt;/RecoveryTools&gt;
        ///&lt;/Recovery&gt; ähnelt.
        /// </summary>
        internal static string WinREConfig {
            get {
                return ResourceManager.GetString("WinREConfig", resourceCulture);
            }
        }
    }
}
